package com.example.todo

import android.app.Application

class ToDoApp: Application() {
    override fun onCreate() {
        super.onCreate()
        if (PreferencesHelper.getToDoList(this).isEmpty()){
            PreferencesHelper.saveToDo(
                listOf(
                    ToDoModel("Android",true),
                    ToDoModel("data class",true),
                    ToDoModel("down to",true),
                    ToDoModel("Nullable",true),
                    ToDoModel("primary constructor",true),
                    ToDoModel("secondary constructor",true),
                    ToDoModel("arrays",true),
                    ToDoModel("activity life cycle",true),
                    ToDoModel("Intent_filter",true),
                    ToDoModel("arrays",true),
                    ToDoModel("Action",true),
                    ToDoModel("percelable",true),
                    ToDoModel("serialisable",true),
                    ToDoModel("Intent",true),
                    ToDoModel("extrast activity",true),
                    ToDoModel("putExtra",true),
                    ToDoModel("getStringExtra",true),
                    ToDoModel("findViewById",true),
                    ToDoModel("SetContetntView",true),
                    ToDoModel("onActivityResult",true),
                    ToDoModel("lateinit vs lazy",true),
                    ToDoModel("object and companion object",true),
                    ToDoModel("options menu, context menu",true),
                    ToDoModel("sharedpreferences",true),
                    ToDoModel("onsaveinstancesstate and onrestoreinstancestate",true),
                    ToDoModel("NitifiyItemChanged",true),
                    ToDoModel("mutable list nima",true),
                    ToDoModel("context nima",true),
                    ToDoModel("View vs ViewGroup",true),
                    ToDoModel("KotlinDataType",true),
                    ToDoModel("onCreate",true),
                    ToDoModel("onRestart",true),
                    ToDoModel("onStart",true),
                    ToDoModel("onResume",true),
                    ToDoModel("onPause",true),
                    ToDoModel("onStop",true),
                    ToDoModel("onDestroy",true),
                    ToDoModel("Intent and Intent Filter",true),
                    ToDoModel("Explicit intent. (Aniq intent).",true),
                    ToDoModel("Implicit intent. (yashirin intent).",true),
                    ToDoModel("putExtra",true),
                    ToDoModel("Service",true),
                    ToDoModel("Broadcast",true),
                    ToDoModel("Shared Preferences",true),
                    ToDoModel("Adapter",true),
                    ToDoModel("Recycle View",true),
                    ToDoModel("setHasFixedSize()",true),
                    ToDoModel("DiffUtil",true),
                    ToDoModel("ItemTouchHelper",true),
                    ToDoModel("ListAdapter",true),
                    ToDoModel("LauncheMode",true),
                    ToDoModel("Fragments",true),
                    ToDoModel("Fragmets lifeCycle",true),
                    ToDoModel("Activity Single and Multi Activity",true),
                    ToDoModel("FragmentManager",true),
                    ToDoModel("Callback nima",true),
                    ToDoModel("Sealed classlar",true),
                    ToDoModel("navHost nima",true),
                    ToDoModel("navGraph nima",true),
                    ToDoModel("Controller nima",true),
                    ToDoModel("Host nima",true),
                    ToDoModel("Benefits and Features",true),
                    ToDoModel("DeepLinking",true),
                    ToDoModel("Animations and transitions",true),
                    ToDoModel("UI patterns",true),
                    ToDoModel("Type Sefety",true),
                    ToDoModel("ViewModel Support",true),
                    ToDoModel("Fragment transactions",true),
                    ToDoModel("Var, Val and Const Val Kotlin",true),
                    ToDoModel("Kotlin Infix keyword",true),
                    ToDoModel("member function and extension functions",true),
                    ToDoModel("\"==\" vs \"===\"",true),
                    ToDoModel("Inline, noinline, crossInline, reified",true),
                    ToDoModel("Value Class",true),
                    ToDoModel("callback",true),
                    ToDoModel("event",true),
                    ToDoModel("handler",true),
                    ToDoModel("typealias",true),
                    ToDoModel("member function",true),
                    ToDoModel("extension function",true),
                ),this
            )
        }
    }
}